<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CigarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CigarRepository extends EntityRepository
{
    public function navCigarSearch($params){
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('c')
            ->from('AppBundle:Cigar','c' )
            ->where('c.name LIKE :name')
            ->setParameter('name', $params . '%');
        $result = $queryBuilder->getQuery()->getResult();

        return $result;
    }


}
