<?php

namespace AppBundle\Repository;

/**
 * CigarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumidorRepository extends \Doctrine\ORM\EntityRepository
{
}