<?php

namespace AppBundle\Repository;

/**
 * ShapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShapeRepository extends \Doctrine\ORM\EntityRepository
{
}
