app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    resource: "@UserBundle/Resources/config/routing/all.xml"